[package]
name = "lazy_crafter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdev = "0.5.1"
x11-clipboard = "0.7.0"
derivative = "2.2.0"
chrono = "0.4.19"
serde_json = "1.0.85"
# serde_derive = "1.0.145"
serde = { version = "1.0", features = ["derive"] }