use lazy_crafter::entities::craft_repo::CraftRepo;
use lazy_crafter::storage::files::local_db::FileRepo;
use std::fs;

#[test]
fn test_autogenerated_mod_ids() {
    let repo = FileRepo::new().unwrap();
    let fixtures = fs::read_to_string("./tests/autogenerated_mod_ids_testcases.txt").unwrap();
    let mut counter = 0;
    let mut mismatches = Vec::new();
    for line in fixtures.lines() {
        let (mod_id, text) = line.split_once(';').expect("mod ID and representation");
        let mut expected: Vec<_> = text.split(';').collect();
        expected.sort_unstable();
        let representation = repo.representation_by_mod_id(mod_id);
        let mut actual: Vec<_> = representation.lines().collect();
        actual.sort_unstable();
        if actual != expected {
            mismatches.push(format!("{mod_id}: expected {expected:?}, got {actual:?}"));
        }
        counter += 1;
    }
    assert!(mismatches.is_empty(), "{}", mismatches.join("\n"));
    assert_eq!(counter, 10_180, "every bundled reference must be checked");
    assert_eq!(
        repo.representation_by_mod_id("missing_mod"),
        "unknown mod: missing_mod"
    );
}
