use lazy_crafter::entities::craft_repo::CraftRepo;
use lazy_crafter::storage::files::local_db::FileRepo;
use std::fs;

#[test]
fn test_autogenerated_mod_ids() {
    let repo = FileRepo::new().unwrap();
    let mut counter = 0;
    for line in fs::read_to_string("./tests/autogenerated_mod_ids_testcases.txt")
        .unwrap()
        .lines()
    {
        let (mod_id, expected) = line.split_once(";").unwrap();
        let repr = repo.representation_by_mod_id(mod_id);
        assert_eq!(repr, expected);
        println!("{}", mod_id);
        counter += 1;
    }
    assert_eq!(counter, 11179)
}
