# This script can create tests from pob data
# https://raw.githubusercontent.com/PathOfBuildingCommunity/PathOfBuilding/dev/src/Data/ModItem.lua

import json
import re

import requests

pattern = '(.*\["(.*)"\] = .* affix = ".*", "(.*)", "(.*)", statOrderKey)|(.*\["(.*)"\] = .* affix = ".*", "(.*)", statOrderKey)'

resp = requests.get(
    "https://raw.githubusercontent.com/PathOfBuildingCommunity/PathOfBuilding/dev/src/Data/ModItem.lua",
    stream=True,
)
with open("tests/autogenerated_mod_ids_testcases.txt", "w") as f:
    for i, line in enumerate(resp.iter_lines()):
        if i < 4 or line == b'}':
            continue
        line = line.decode()
        if ('weightKey = { "default", }, weightVal = { 0 },' in line):
            continue

        cap = re.search(pattern, line)
        if not cap:
            print(line)
            raise Exception(f"{line}")
        g2 = cap.group(2)
        g3 = cap.group(3)
        g4 = cap.group(4)

        g6 = cap.group(6)
        g7 = cap.group(7)
        if g2 and g3 and g4:
            f.write(f"{g2};{g3};{g4}\n")
        elif g6 and g7:
            f.write(f"{g6};{g7}\n")
        else:
            print(line)
            raise Exception(f"{line}")
