# This script can create tests from pob data
# https://raw.githubusercontent.com/PathOfBuildingCommunity/PathOfBuilding/dev/src/Data/ModItem.lua

import json
import re

import requests

pattern = '.*\["(.*)"\] = .* affix = ".*", "(.*)", statOrderKey'

resp = requests.get(
    "https://raw.githubusercontent.com/PathOfBuildingCommunity/PathOfBuilding/dev/src/Data/ModItem.lua",
    stream=True,
)
with open("tests/autogenerated_mod_ids_testcases.txt", "w") as f:
    for line in resp.iter_lines():
        cap = re.search(pattern, line.decode())
        if not cap:
            continue
        g1 = cap.group(1)
        g2 = cap.group(2)
        if g1 and g2:
            f.write(f"{g1};{g2}\n")
